language: c

os:
  - linux
  - osx

compiler:
  - clang

addons:
  apt:
    packages:
      - libsdl2-dev
      - mesa-utils

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

script:
  - CONFIG_SDL2=true CONFIG_HTTP=true SDL_LIBS=$(sdl2-config --static-libs) make

